### ISSUE TITLE
MARK III: Improve styling on login scene and selectPartner scene

### ISSUE THREAD

**Issue by vatteh** [Laybium/laybium#125]
![whatsapp image 2016-12-06 at 9 20 37 pm](https://cloud.githubusercontent.com/assets/4132331/20994548/15d9765e-bcbf-11e6-86a9-7faf153515e9.jpeg)

**Comment by quinnliu** [comment]
### Made it fit on iPhone 5, iPhone 6, and iPhone 6 Plus screen

- ![simulator screen shot dec 20 2016 12 41 09 pm](https://cloud.githubusercontent.com/assets/2585159/21363310/9f546938-c6b1-11e6-8159-5b7c24fc1ae4.png)

- ![simulator screen shot dec 20 2016 12 41 10 pm](https://cloud.githubusercontent.com/assets/2585159/21363327/b1764db6-c6b1-11e6-8426-156d018e535b.png)

**Comment by quinnliu** [comment]
- [x] make intial screen random black or white

**Comment by vatteh** [comment]
Merged into develop branch

**Comment by quinnliu** [comment]
nice
