### ISSUE TITLE
Installing React Native Android on Windows Tips

### ISSUE THREAD

**Issue by quinnliu** [Laybium/laybium#132]
- [x] install react native for android on Windows [here](https://facebook.github.io/react-native/docs/getting-started.html#content)
- [x] helpful install [tips](https://shift.infinite.red/getting-started-with-react-native-development-on-windows-90d85a72ae65#.481jcxrnh)
- [x] AVD Manager greyed out on Hunter's laptop
   - [x] after running react-native init project the avd manager in Android studio worked
   - [x] additional instructions for setting up Android for React Native on Windows missing in docs
          [here](http://stackoverflow.com/questions/11350692/android-is-not-recognized-as-an-internal-or-external-command)
   - [x] HAXM is not installed on this machine. follow [instructions](http://stackoverflow.com/questions/29136173/emulator-error-x86-emulation-currently-requires-hardware-acceleration)

- [x] Simulator on 6GB Memory is too slow so load app onto phone directly
   - [x] connect adb command in PATH first [here](http://stackoverflow.com/questions/10303639/adb-command-not-found)
   - [x] [link](https://facebook.github.io/react-native/docs/running-on-device.html)
   - [x] use `react-native run-android --configuration=release` based on [here](http://stackoverflow.com/questions/41263330/error-running-react-native-run-android-variant-release-task-installreleasede) DIDN'T WORK

- [x] 192.168.1.17:8081 didn't work.

**Comment by Hunter690** [comment]
- [ ] first thing
- [ ] second thing
- [ ] grow some balls

**Comment by quinnliu** [comment]
`cd folerYouWantToGoTo`

**Comment by quinnliu** [comment]
close for now
