### ISSUE TITLE
MARK II: display available partners and connect with them

### ISSUE THREAD

**Issue by quinnliu** [Laybium/laybium#19]
TODO List:
- [x] Display available partners on phoneA and phoneB
  - [x] 1) client makes web socket request to server asking for list of `available_partners`(dynamic).
     - [x] 2) server needs to respond with available partners
        - [x] 2.1) server needs to make sure both iphones have the most up to date list of available
               partners that are on screen 2
        - [x] 2.2) I can only show a user as available if they are also on selectPartnerScene
  - [x] 3) on client if no partners show `No Available Partners aka our app SUCKS too much`
  - [x] 4) every time `availble_partners` is changed we must update the list on all iphone's on `SelectPartnerScene`

- [x] right now just implement click to connect with no asking for confirmation since logic is a lot
   - [x] make every username on `selectPartnerScene` a `TouchableHighlight`
   - on simulator loading app on iPhone 5s, 6, and 6s

### additional
- [x] store which screen everyone is one for several edge cases of using app
- [x] when user on select partner screen presses back button the server needs to update the state on the server to show they are no longer on screen `selectPartnerScene`
   - [x] problem solved by not having a back button right now haha
   - for running multiple simulations of the app [here](http://stackoverflow.com/questions/26446346/xcode6-run-two-instances-of-the-simulator)
```
cd /Applications/Xcode.app/Contents/Developer/Applications
open -n Simulator.app
```

**Comment by quinnliu** [comment]
<img width="512" alt="screen shot 2016-10-10 at 12 38 58 am" src="https://cloud.githubusercontent.com/assets/2585159/19224231/fbcae81c-8e81-11e6-8725-e1752827d88f.png">

**Comment by quinnliu** [comment]
- [ ] store which screen everyone is one for several edge cases of using app

**Comment by quinnliu** [comment]
# for task 2.1 & 2.2 
![img_1219](https://cloud.githubusercontent.com/assets/2585159/19477301/c679b306-953d-11e6-9548-50be8366db30.JPG)

**Comment by quinnliu** [comment]
@vatteh we should consider what you said and put all the state into 1 data structure. We can move the client websockets into the file model and just call methods on it so we can abstract the model.

**Comment by vatteh** [comment]
Ok cool. If you feel you need to implement this now, you can go ahead and implement this. If you need help, we can work on this together the next time we meet. This isn't as urgent for me as I'm still researching song download access.

**Comment by quinnliu** [comment]
- [ ] if userA clicks userB on userA's phone then userA and userB are automatically sent to `selectSongScene`

**Comment by quinnliu** [comment]
![img_3867](https://cloud.githubusercontent.com/assets/2585159/19728078/50359254-9b92-11e6-9537-e9227bb8fdd1.jpeg)

**Comment by quinnliu** [comment]
![img_3867](https://cloud.githubusercontent.com/assets/2585159/19728101/6842175a-9b92-11e6-8c52-b68d29a7d5a9.jpeg)

**Comment by quinnliu** [comment]
@t=1 on server, the server receives message from Q's iPhone saying Q & Victor are partners. The server's state goes from:

@t = 0.9 
```
{
  "Q": {
    "onScreen": "selectPartnerScene"
  },
  "Victor": {
    "onScreen": "selectPartnerScene"
  }
}
```

**Comment by quinnliu** [comment]
@t = 1.1
```
usersHashtable =
{
  "Q": {
    "onScreen": "selectSongScene"
  },
  "Victor": {
    "onScreen": "selectSongScene"
  }
}
```

**Comment by quinnliu** [comment]
- [ ] clientA sends correct partnering message to server to partner with clientB
- [ ] server stores information correclty
- [ ] server updates clientA and clientB with message to move to select song scene 
- [ ] both clients move to select song scene

**Comment by quinnliu** [comment]
DONE !!!!!
