### ISSUE TITLE
MARK II: display possible songs

### ISSUE THREAD

**Issue by quinnliu** [Laybium/laybium#25]
- [x] sent e-mail to z@zmxv.com with issue linked
- use this trick to simulate 2+ iphones on your computer [here](http://stackoverflow.com/questions/26446346/xcode6-run-two-instances-of-the-simulator)

**Comment by vatteh** [comment]
Native filesystem access for react-native: https://github.com/johanneslumpe/react-native-fs
iTunes module for React Native: https://github.com/kadiks/react-native-itunes
iOS SDK: Music Library Access: https://code.tutsplus.com/tutorials/ios-sdk-music-library-access--mobile-6188
how can i search all sound files in iphone through xcode: http://stackoverflow.com/questions/16828218/how-can-i-search-all-sound-files-in-iphone-through-xcode
MPMediaItem: https://developer.apple.com/reference/mediaplayer/mpmediaitem
Save mp3 file into iphone music library: http://stackoverflow.com/questions/13209618/save-mp3-file-into-iphone-music-library
react-native-music-control: https://www.npmjs.com/package/react-native-music-control

**Comment by quinnliu** [comment]
Using React-native-fs library we get:
```
2016-10-26 00:56:48.770 [info][tid:com.facebook.react.JavaScript] found MP3 file adorn_by_miguel.mp3 located at: /Users/appollo_liu/Library/Developer/CoreSimulator/Devices/6FB93256-6B1F-4D57-8668-E50BC4B7A1C0/data/Containers/Bundle/Application/69BC641F-A770-429F-9823-B55E590D8C64/laybium.app/adorn_by_miguel.mp3
```

**Comment by quinnliu** [comment]
- [ ] display as many .mp3 files as possible from Q's iPhone 
- [ ] look in the iPhone's downloads folder from messages first
- [ ] automatically find all possible syncable songs
- [ ]  ask author of react-native-sound library if he knows [here](https://github.com/zmxv/react-native-sound/issues/78)

**Comment by quinnliu** [comment]
moved  consider using react-native-sound & react-native-itunes together to play songs from itunes to new issue
