### ISSUE TITLE
automatically generate username and ask for approval

### ISSUE THREAD

**Issue by quinnliu** [Laybium/laybium#4]
refer to screen 1: https://cloud.githubusercontent.com/assets/2585159/18612570/b4fc07de-7d2b-11e6-9eb6-c6c127fa9fd7.JPG

**Comment by quinnliu** [comment]
I think we should automatically suggest a username. Like 
`lovely purple lion`

adjective * adjective * noun
 
about 500 common adjectives: http://www.talkenglish.com/vocabulary/top-500-adjectives.aspx

**Comment by quinnliu** [comment]
TODO: move redux react code into it's own folder `src` at top level

**Comment by quinnliu** [comment]
TODO: create unique redux files for each screen.

**Comment by quinnliu** [comment]
using `NavigatorIOS` here: https://facebook.github.io/react-native/docs/navigatorios.html

**Comment by quinnliu** [comment]
`npm cache clean && watchman watch-del-all && rm -rf node_modules && npm install && npm start -- --reset-cache`

**Comment by quinnliu** [comment]
NOTE: if you go to github react-native and find a branch that is stable and use the react-native version with react version in your package.json without `^` or `~` you can get a npm install with no errors. Example: https://github.com/facebook/react-native/blob/0.26-stable/package.json has react version 15.0.2 and react-native version 0.26.3

**Comment by quinnliu** [comment]
TODO: 
- [ ] get `react-native-router-flux` to build app successfully
- [ ] create unique redux files for each screen. 
  + using `NavigatorIOS` [here](https://facebook.github.io/react-native/docs/navigatorios.html)
  + follow up [stackoverflow](http://stackoverflow.com/questions/39729687/in-react-native-how-to-pass-store-to-component-when-using-navigatorios) TODO: Q planning on putting a bounty
  + if bounty isn't answer consider using wix open source navigation library [here](https://github.com/wix/react-native-controllers#why-do-we-need-this-package)
  + now considering new library `react-native-router-flux` instead of `NavigatorIOS` [here](https://github.com/aksonov/react-native-router-flux/blob/master/docs/REDUX_FLUX.md)
- [ ] remove usernames from hashtable of used usernames when each client leaves

**Comment by quinnliu** [comment]
possible solution for error [UNMET PEER DEPENDENCY](http://stackoverflow.com/questions/35738346/how-to-solve-npm-unmet-peer-dependency)

**Comment by quinnliu** [comment]
HOOOOOOOOOOOOLLLLYYY MOOOOTHTTTTTTHHHHEEERRR OOOOFFFF GGGGOOODDDD ITTTTSSS WORKRRINGGGG

**Comment by quinnliu** [comment]
TODO List
- [ ] need to establish connection on pageOne. 
   + [ ] Client websocket code in actions/audioPlayer.js needs to be moved?
- [ ] remove usernames from hashtable of used usernames when each client leaves

**Comment by quinnliu** [comment]
```const initialState = {
	count: null,
	isLoading: true,
	createGroupError: null,
	isCreateGroupLoading: false,
	isCreateGroupShown: false,
	groups: []
};

export default function reducer(state = initialState, action) {
	if (!action) {
		return state;
	}

	switch (action.type) {
		case actionTypes.START_LOADING_GROUPS: {
			return _.assign({}, state, {
				isLoading: true
			});
		}```

**Comment by vatteh** [comment]
Completed
