### ISSUE TITLE
MARK II: Upgrade Style and UI

### ISSUE THREAD

**Issue by vatteh** [Laybium/laybium#71]
Upgrade the styles and UI to a more presentable state.
- [x] https://facebook.github.io/react-native/docs/flexbox.html
- [x] add manual part to install instructions [here](https://github.com/oblador/react-native-vector-icons#installation)
- [x] start working for branch `issue-71-sytle` so merge it back into `issue-71` after you have UI working again
- [x] implemented #69 
- [x] select song code is breaking [tutorial](https://medium.com/differential/react-native-basics-how-to-use-the-listview-component-a0ec44cf1fe8#.mmfs59f5b)
- [x] read through Facebook react native style [tutorials](https://facebook.github.io/react-native/docs/style.html)
- [x] fix secret section

**Comment by quinnliu** [comment]
Congrats we did it !!!!!!!
